# Pandas Tutorial
### Sorting Data
**Source:**

Corey Schafer - [Python Pandas Playlist](https://www.youtube.com/playlist?list=PL-osiE80TeTsWmV9i9c58mdDCSskIFdDS)

In [64]:
import pandas as pd

### Creating a sample DataFrame

In [65]:
people = {
    "first" : ["Parampreet", "Corey", "Anant"],
    "last" : ["Singh", "Schafer", "Luthra"],
    "email" : ["ParampreetSingh@gmail.com", "CoreySchafer@gmail.com", "AnantLuthra@gmail.com"]
}

In [66]:
df = pd.DataFrame(people)
df

        first     last                      email
0  Parampreet    Singh  ParampreetSingh@gmail.com
1       Corey  Schafer     CoreySchafer@gmail.com
2       Anant   Luthra      AnantLuthra@gmail.com

### Use `.sort_values()` to sort the data
- In `by` parameter, we provide the column name by which the data is to be sorted.
- To sort the data in descending order, we can set `ascending` parameter to `False`.

In [67]:
df.sort_values(by="last")

        first     last                      email
2       Anant   Luthra      AnantLuthra@gmail.com
1       Corey  Schafer     CoreySchafer@gmail.com
0  Parampreet    Singh  ParampreetSingh@gmail.com

In [68]:
df.sort_values(by="first", ascending=False)

        first     last                      email
0  Parampreet    Singh  ParampreetSingh@gmail.com
1       Corey  Schafer     CoreySchafer@gmail.com
2       Anant   Luthra      AnantLuthra@gmail.com

In [69]:
df.loc[3] = ["Param", "Singh", "ParamSingh@gmail.com"]
df.loc[4] = {"last" : "Singh", "first" : "Karan", "email" : "KaranSingh@email.com"}

In [70]:
df

        first     last                      email
0  Parampreet    Singh  ParampreetSingh@gmail.com
1       Corey  Schafer     CoreySchafer@gmail.com
2       Anant   Luthra      AnantLuthra@gmail.com
3       Param    Singh       ParamSingh@gmail.com
4       Karan    Singh       KaranSingh@email.com

#### If we want to sort data on multiple columns
**Reason**: If we have identical data on a column, then we will sort on multiple columns.
- We pass a list of columns in the `by` parameter of `.sort_values()` method.
- The sort will be done based on the order of the column names in the list.

In [71]:
df.sort_values(by=["last", "first"], inplace=True)

In [72]:
# reseting the index
df.reset_index(drop=True, inplace=True)

In [73]:
df

        first     last                      email
0       Anant   Luthra      AnantLuthra@gmail.com
1       Corey  Schafer     CoreySchafer@gmail.com
2       Karan    Singh       KaranSingh@email.com
3       Param    Singh       ParamSingh@gmail.com
4  Parampreet    Singh  ParampreetSingh@gmail.com

#### If we want to sort multiple columns and some columns in ascending and some in descending order
- We will pass the list to the `ascending` parameter of booleans.
- `False` means sort in `descending` order, `True` to sort in `ascending` order.

In [74]:
df.sort_values(by=["last", "first"], ascending=[False, True])

        first     last                      email
2       Karan    Singh       KaranSingh@email.com
3       Param    Singh       ParamSingh@gmail.com
4  Parampreet    Singh  ParampreetSingh@gmail.com
1       Corey  Schafer     CoreySchafer@gmail.com
0       Anant   Luthra      AnantLuthra@gmail.com

### To sort the data based on index, use `.sort_index()` method

In [75]:
df.sort_index()

        first     last                      email
0       Anant   Luthra      AnantLuthra@gmail.com
1       Corey  Schafer     CoreySchafer@gmail.com
2       Karan    Singh       KaranSingh@email.com
3       Param    Singh       ParamSingh@gmail.com
4  Parampreet    Singh  ParampreetSingh@gmail.com

### To sort a specific row/series, use `.sort_values()` on the row/series.

In [82]:
df["last"].sort_values(ascending=False).reset_index(drop=True)

0      Singh
1      Singh
2      Singh
3    Schafer
4     Luthra
Name: last, dtype: object

### DataFrames of StackOverflow survey result 2021

In [83]:
df = pd.read_csv("./data/survey_results_public.csv", index_col="ResponseId")
schema_df = pd.read_csv("./data/survey_results_schema.csv", index_col="qname")

In [84]:
pd.set_option("display.max_columns", df.shape[1])

In [85]:
df.head()

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,NaN,NaN,NaN,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,NaN,Cordova,NaN,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,Flask,NumPy;Pandas;TensorFlow;Torch/PyTorch,Keras;NumPy;Pandas;TensorFlow;Torch/PyTorch,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,Angular;jQuery,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,Flask,Apache Spark;Hadoop;NumPy;Pandas,Hadoop;NumPy;Pandas,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [86]:
df.columns

Index(['MainBranch', 'Employment', 'Country', 'US_State', 'UK_Country',
       'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode', 'YearsCodePro',
       'DevType', 'OrgSize', 'Currency', 'CompTotal', 'CompFreq',
       'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [87]:
# Sorting the data based on the Country column
df.sort_values(by="Country", inplace=True)

In [89]:
df.sample(10)

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
16461,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",45 - 54 years,Online Courses or Certification;Books / Physic...,26,20,"Developer, mobile;Developer, front-end;Develop...","10,000 or more employees",INR\tIndian rupee,NaN,Monthly,Java;JavaScript,Java;JavaScript,MySQL,MySQL,AWS,AWS,Spring,React.js,NaN,NaN,Git,Docker;Kubernetes;Yarn,Android Studio;Atom;Eclipse;Visual Studio Code,Visual Studio Code,Linux-based,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,45-54 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
79593,I am a developer by profession,Employed full-time,Sweden,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,School,27,21,"Developer, desktop or enterprise applications;...",20 to 99 employees,SEK\tSwedish krona,NaN,Monthly,C#;C++;Java,Java,PostgreSQL,PostgreSQL,NaN,NaN,NaN,NaN,NaN,NaN,Git;Unreal Engine,Git;Unreal Engine,IntelliJ;Sublime Text,IntelliJ;Sublime Text,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,Yes,Less than once per month or monthly,"Yes, somewhat",No,45-54 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
72394,I am a student who is learning to code,"Not employed, but looking for work",India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,4,NaN,"Engineer, data;Data scientist or machine learn...",NaN,NaN,NaN,NaN,C;C#;C++;COBOL;HTML/CSS;Java;JavaScript;Kotlin...,Python;R;SQL;VBA,MySQL;SQLite,IBM DB2;Microsoft SQL Server;MySQL;SQLite,AWS;DigitalOcean;Google Cloud Platform;IBM Clo...,AWS;Google Cloud Platform;Heroku;IBM Cloud or ...,Angular.js;Django;Flask,FastAPI;Flask,NumPy;Pandas;Torch/PyTorch,Apache Spark;Hadoop;NumPy;Pandas;Torch/PyTorch,Git;Unity 3D;Unreal Engine,Docker;Git,Android Studio;Atom;Eclipse;IntelliJ;IPython/J...,IPython/Jupyter;RStudio;Visual Studio Code,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
10867,None of these,Employed full-time,Indonesia,NaN,NaN,Something else,11 - 17 years,Other (please specify):,20,20,"Developer, mobile;Developer, front-end;Develop...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AWS,AWS;DigitalOcean;Google Cloud Platform;Heroku;...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,I have never visited Stack Overflow or the Sta...,NaN,NaN,NaN,NaN,No,35-44 years old,Man,No,Prefer to self-describe:,South Asian;Hispanic or Latino/a/x;Middle East...,I am deaf / hard of hearing;I am blind / have ...,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN
68930,I am a developer by profession,Employed full-time,United States of America,Michigan,NaN,Some college/university study without earning ...,11 - 17 years,"Other online resources (ex: videos, blogs, etc...",15,9,"Developer, front-end;Developer, full-stack;Dev...","10,000 or more employees",USD\tUnited States dollar,80000.0,Yearly,Bash/Shell;C#;HTML/CSS;JavaScript;Node.js;SQL;...,Bash/Shell;C#;HTML/CSS;JavaScript;Node.js;Pyth...,MariaDB;Microsoft SQL Server;MongoDB;MySQL;Pos...,Microsoft SQL Server;PostgreSQL;Redis,NaN,NaN,Angular.js;ASP.NET;ASP.NET Core ;Express;jQuery,Angular.js;ASP.NET;ASP.NET Core ;Express,.NET Framework;.NET Core / .NET 5,.NET Core / .NET 5,Git,Git,Sublime Text;Visual Studio;Visual Studio Code,Rider;Sublime Text;Visual Studio Code,MacOS,Go for a walk or other physical activity;Googl...,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,A few times per week,"No, not really",No,25-34 years old,Man,No,Bisexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,80000.0
5025,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",18,Less than 1 year,"Developer, front-end;Developer, full-stack;Dev...","Just me - I am a freelancer, sole proprietor, ...",CAD\tCanadian dollar,1000.0,Weekly,C#;Rust,C#;Rust,DynamoDB;Redis,DynamoDB;PostgreSQL;Redis,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Git,Docker;Git;Kubernetes,Visual Studio Code,NaN,Linux-based,Go for a walk or other physical activity;Googl...,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,37800.0
7384,I am a developer by profession,"Independent contractor, freelancer, or self-em...",India,NaN,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,14,7,"Developer, mobile;Developer, back-end;Develope...","Just me - I am a freelancer, sole proprietor, ...",INR\tIndian rupee,50000.0,Monthly,Java;Kotlin;Python,Dart,Firebase,PostgreSQL,NaN,NaN,NaN,NaN,NaN,NaN,Git,Docker,Android Studio;PyCharm;Sublime Text,NaN,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Daily or almost daily,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,8376.0
70120,I am a student who is learning to code,Employed part-time,Mexico,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",5,NaN,"Developer, back-end;Student",NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Node.js;SQL,Python,PostgreSQL,Elasticsearch;Firebase;MariaDB;MongoDB,Heroku;Microsoft Azure,AWS,NaN,NaN,NaN,NaN,NaN,NaN,Android Studio;NetBeans;Notepad++;Visual Studi...,Vim,Windows,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,"No, not really",Yes,18-24 years old,Man,No,NaN,Hispanic or Latino/a/x,None of the above,Prefer not to say,Appropriate in length,Neither easy nor difficult,NaN
29547,"I am not primarily a developer, but I write co...","Student, part-time",Turkey,NaN,NaN,"Secondary school (e.g. American high school, G...",5 - 10 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,C#;JavaScript;SQL,C;C#;C++;Python,MySQL;SQLite,MySQL,DigitalOcean,DigitalOcean,ASP.NET;ASP.NET Core ;Flask,ASP.NET Core,.NET Framework;.NET Core / .NET 5,.NET Framework;.NET Core / .NET 5;TensorFlow,Docker;Unity 3D;Xamarin,Docker;Unity 3D;Xamarin,Sublime Text;Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Yes,A few times per month or weekly,"Yes, somewhat",No,Under 18 years old,Man,No,Bisexual,I don't know,I am blind / have difficulty seeing,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Easy,NaN
4328,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School,9,3,"Developer, mobile;Developer, front-end;Develop...","1,000 to 4,999 employees",INR\tIndian rupee,NaN,Monthly,C;C++;Dart;Go;HTML/CSS;JavaScript;Node.js;Rust...,C;C++;Dart;Go;HTML/CSS;JavaScript;Node.js;Rust...,Cassandra;Firebase;MongoDB;PostgreSQL;Redis,Cassandra;Firebase;MongoDB;PostgreSQL;Redis,NaN,NaN,Express;FastAPI;React.js;Svelte,Express;FastAPI;React.js;Svelte,Flutter;React Native,Flutter;React Native,Deno;Git;Yarn,Deno;Git;Kubernetes;Yarn,Android Studio;Visual Studio Code,Visual Studio Code;Xcode,Linux-based,Visit Stack Overflow;Google it,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Less than once per month or monthly,"No, not really",Yes,18-24 years old,Man,No,Straight / Heterosexual,Southeast Asian,None of the above,None of the above,Appropriate in length,Easy,NaN

In [93]:
df["Country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Congo, Republic of the...', 'Costa Rica', 'Croatia', 'Cuba',
       'Cyprus', 'Czech Republic', "Côte d'Ivoire",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala',
       'Guinea', 'Guyana', 'Haiti', 'Honduras', 'Hong Kong (S.A.R.)',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran, Islamic Republic of...', 'Iraq', 'Ireland', 'Isle of Man',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kosovo', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libyan Arab Jamahiriya', 'Liechtenstein', 'Lithuania',
       'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
       'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia, Federated States of...', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia',
       'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger',
       'Nigeria', 'Nomadic', 'North Korea', 'Norway', 'Oman', 'Pakistan',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Poland', 'Portugal', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'Romania', 'Russian Federation', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'San Marino', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Somalia', 'South Africa', 'South Korea', 'Spain',
       'Sri Lanka', 'Sudan', 'Suriname', 'Swaziland', 'Sweden',
       'Switzerland', 'Syrian Arab Republic', 'Taiwan', 'Tajikistan',
       'Thailand', 'The former Yugoslav Republic of Macedonia', 'Togo',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'Uzbekistan', 'Venezuela, Bolivarian Republic of...',
       'Viet Nam', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [94]:
df.sort_values(by=["Country", "ConvertedCompYearly"], ascending=[True, False], inplace=True)

In [95]:
df.head()

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
65400,I am a developer by profession,Employed full-time,Afghanistan,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",25 - 34 years,Online Courses or Certification,7,3,"Developer, desktop or enterprise applications;...",500 to 999 employees,ANG Netherlands Antillean guilder,4544242.0,Monthly,Bash/Shell;C++;Elixir;LISP;Node.js;Ruby;Rust;S...,Clojure;Crystal;Dart;Matlab;Node.js;Python;R,Couchbase;Elasticsearch;MariaDB,MySQL;Oracle,AWS;IBM Cloud or Watson,Oracle Cloud Infrastructure,ASP.NET;Drupal;Laravel;Svelte,Angular;ASP.NET;Django;Express;Flask;jQuery;Ru...,.NET Framework;Apache Spark;Hadoop;Pandas,Flutter;Pandas;Qt,Docker;Flow;Terraform,Chef;Docker;Git,NetBeans;PHPStorm;RubyMine,Eclipse;NetBeans,Linux-based,Watch help / tutorial videos;Play games,Stack Overflow;Stack Overflow for Teams (priva...,A few times per month or weekly,Not sure/can't remember,NaN,"No, not at all",Yes,35-44 years old,"Man;Non-binary, genderqueer, or gender non-con...",Yes,Bisexual;Prefer to self-describe:;Gay or Lesbi...,South Asian;Hispanic or Latino/a/x;Black or of...,I am unable to / find it difficult to walk or ...,I have a mood or emotional disorder (e.g. depr...,Too short,Difficult,30468516.0
22667,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Afghanistan,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",45 - 54 years,School,5,Less than 1 year,System administrator,"Just me - I am a freelancer, sole proprietor, ...",AFN\tAfghan afghani,1000000.0,Monthly,Assembly;C#;C++;JavaScript;VBA,HTML/CSS;Java;PHP;Python;R;SQL,Microsoft SQL Server,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Windows,Visit another developer community (please name):,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,45-54 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,155496.0
27199,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Afghanistan,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Online Courses or Certification,3,3,Academic researcher;Student,20 to 99 employees,JPY\tJapanese yen,480000.0,Monthly,Go;JavaScript;Python,Go;JavaScript;Python,MySQL,MySQL,Google Cloud Platform,Google Cloud Platform,Express;React.js,Express;React.js,React Native,React Native,Docker;Git;Pulumi,Docker,Visual Studio,Visual Studio,Linux-based,Visit Stack Overflow,Stack Exchange,A few times per month or weekly,No,NaN,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,East Asian,Prefer not to say,Prefer not to say,Too long,Difficult,51804.0
31087,I am a developer by profession,Employed full-time,Afghanistan,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",16,13,"Developer, mobile;Developer, front-end;Develop...",500 to 999 employees,AFN\tAfghan afghani,154100.0,Monthly,HTML/CSS;JavaScript;Node.js;PHP;SQL;VBA,HTML/CSS;JavaScript;Kotlin;Node.js;Objective-C...,Firebase;MariaDB;MySQL;Redis;SQLite,Couchbase;DynamoDB;Elasticsearch;Firebase;Mari...,AWS;DigitalOcean,Microsoft Azure,Express;jQuery;Laravel;Vue.js,jQuery;Laravel;React.js;Svelte;Vue.js,Cordova,Flutter;React Native,Docker;Git;Puppet;Yarn,Docker;Git;Kubernetes;Terraform;Yarn,Android Studio;NetBeans;Notepad++;Sublime Text...,Android Studio;Sublime Text;Vim;Visual Studio ...,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Too long,Neither easy nor difficult,23964.0
44641,I am a developer by profession,Employed full-time,Afghanistan,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification,7,6,"Developer, full-stack",10 to 19 employees,AFN\tAfghan afghani,97333.0,Monthly,C#;HTML/CSS;JavaScript;PHP;SQL,C#;Dart;HTML/CSS;JavaScript;PHP;Python;SQL,MariaDB;Microsoft SQL Server;MySQL,Firebase;MariaDB;Microsoft SQL Server;MongoDB;...,AWS,AWS;Google Cloud Platform;Microsoft Azure,ASP.NET;ASP.NET Core ;jQuery;Laravel;Vue.js,Angular;ASP.NET Core ;Django;jQuery;Laravel;Re...,.NET Framework;.NET Core / .NET 5,.NET Core / .NET 5;Flutter;NumPy;Pandas;Qt;Ten...,Git;Yarn,Docker;Git;Xamarin;Yarn,PHPStorm;Visual Studio;Visual Studio Code;Webs...,Android Studio;PHPStorm;PyCharm;Rider;Visual S...,MacOS,Visit Stack Overflow;Google it;Meditate,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,East Asian,None of the above,None of the above,Too long,Neither easy nor difficult,15132.0

### To get first `n` largest/smallest of a column, we use `.nlargest()` / `.nsmallest()`

In [111]:
df["ConvertedCompYearly"].nlargest(10)

ResponseId
66911    45241312.0
65400    30468516.0
40587    21822250.0
28792    20000000.0
12701    19200000.0
9609     17500000.0
5306     15000000.0
12904    14411628.0
66489    12750000.0
47564    12500000.0
Name: ConvertedCompYearly, dtype: float64

In [105]:
df["ConvertedCompYearly"].nlargest(10, keep="first")

ResponseId
66911    45241312.0
65400    30468516.0
40587    21822250.0
28792    20000000.0
12701    19200000.0
9609     17500000.0
5306     15000000.0
12904    14411628.0
66489    12750000.0
47564    12500000.0
Name: ConvertedCompYearly, dtype: float64

#### To get first n largest/smalles with all the columns based on one column, we use `.nlargest()`/`.nsmallest()` on Dataframes.

In [112]:
df.nlargest(10, columns="ConvertedCompYearly")

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,WebframeWantToWorkWith,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
66911,I am a developer by profession,I prefer not to say,Belgium,NaN,NaN,Primary/elementary school,55 - 64 years,Books / Physical media,1,21,NaN,"Just me - I am a freelancer, sole proprietor, ...",ALL\tAlbanian lek,5.123468e+09,Yearly,APL,NaN,Couchbase,NaN,AWS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IntelliJ;PyCharm,NaN,Other (please specify):,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow for Teams (private knowledge sh...,Less than once per month or monthly,Yes,I have never participated in Q&A on Stack Over...,"No, not at all",Yes,55-64 years old,NaN,Yes,NaN,Black or of African descent,I am blind / have difficulty seeing,I have a concentration and/or memory disorder ...,Too short,NaN,45241312.0
65400,I am a developer by profession,Employed full-time,Afghanistan,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",25 - 34 years,Online Courses or Certification,7,3,"Developer, desktop or enterprise applications;...",500 to 999 employees,ANG Netherlands Antillean guilder,4.544242e+06,Monthly,Bash/Shell;C++;Elixir;LISP;Node.js;Ruby;Rust;S...,Clojure;Crystal;Dart;Matlab;Node.js;Python;R,Couchbase;Elasticsearch;MariaDB,MySQL;Oracle,AWS;IBM Cloud or Watson,Oracle Cloud Infrastructure,ASP.NET;Drupal;Laravel;Svelte,Angular;ASP.NET;Django;Express;Flask;jQuery;Ru...,.NET Framework;Apache Spark;Hadoop;Pandas,Flutter;Pandas;Qt,Docker;Flow;Terraform,Chef;Docker;Git,NetBeans;PHPStorm;RubyMine,Eclipse;NetBeans,Linux-based,Watch help / tutorial videos;Play games,Stack Overflow;Stack Overflow for Teams (priva...,A few times per month or weekly,Not sure/can't remember,NaN,"No, not at all",Yes,35-44 years old,"Man;Non-binary, genderqueer, or gender non-con...",Yes,Bisexual;Prefer to self-describe:;Gay or Lesbi...,South Asian;Hispanic or Latino/a/x;Black or of...,I am unable to / find it difficult to walk or ...,I have a mood or emotional disorder (e.g. depr...,Too short,Difficult,30468516.0
40587,I am a developer by profession,Employed full-time,United States of America,California,NaN,Some college/university study without earning ...,Younger than 5 years,"Other online resources (ex: videos, blogs, etc...",37,13,Other (please specify):,"10,000 or more employees",USD\tUnited States dollar,4.364450e+05,Weekly,Bash/Shell;HTML/CSS;Java;JavaScript;Node.js;Py...,Bash/Shell;Haskell;HTML/CSS;Java;JavaScript;No...,MariaDB;MySQL;SQLite,MariaDB;MySQL;SQLite,Microsoft Azure,Microsoft Azure,Flask,Express;Flask;React.js;Svelte,NaN,NaN,Git,Docker;Git,IntelliJ;Visual Studio Code,IntelliJ;Visual Studio;Visual Studio Code,MacOS,Visit Stack Overflow;Google it;Do other work a...,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, somewhat",Yes,35-44 years old,Man,No,Bisexual,White or of European descent,I am blind / have difficulty seeing,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,21822250.0
28792,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",35 - 44 years,Coding Bootcamp;Other online resources (ex: vi...,11,9,"Developer, desktop or enterprise applications;...",100 to 499 employees,USD\tUnited States dollar,2.000000e+07,Yearly,C#;C++;Groovy;HTML/CSS;Java;JavaScript;Node.js...,Ruby;Swift,Microsoft SQL Server;MySQL;Oracle;PostgreSQL;S...,MongoDB,AWS;DigitalOcean;Heroku,IBM Cloud or Watson;Microsoft Azure,Angular.js;Drupal;Laravel;Ruby on Rails;Symfony,Angular;ASP.NET,Apache Spark;Cordova;Hadoop,.NET Framework,Git,Chef;Docker;Kubernetes;Puppet,Android Studio;Atom;Eclipse;IPython/Jupyter;Ne...,Visual Studio Code,MacOS,Visit Stack Overflow;Google it;Visit another d...,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per month or weekly,Yes,A few times per month or weekly,Neutral,Yes,35-44 years old,Man,No,Prefer not to say,Prefer not to say,Prefer not to say,None of the above,Appropriate in length,Easy,20000000.0
12701,I am a developer by profession,Employed full-time,India,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",25 - 34 years,Online Forum,5,5,"Developer, full-stack",100 to 499 employees,USD\tUnited States dollar,1.600000e+06,Monthly,JavaScript,JavaScript,MongoDB;MySQL;PostgreSQL,MongoDB;MySQL;PostgreSQL,AWS;Heroku,AWS;Heroku,React.js,React.js,NaN,NaN,Git,Git,Eclipse;Visual Studio Code,Eclipse;Visual Studio Code,Windows,Visit Stack Overflow;Google it;Visit another d...,Stack Exchange,A few times per week,Yes,A few times per week,Neutral,Yes,35-44 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,19200000.0
9609,"I am not primarily a developer, but I write co...",Employed full-time,United States of America,New York,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,School,25,21,"Senior Executive (C-Suite, VP, etc.)",20 to 99 employees,USD\tUnited States dollar,3.500000e+05,Weekly,Bash/Shell;Go;HTML/CSS;Java;JavaScript;Kotlin;...,NaN,Elasticsearch;IBM DB2;MariaDB;MongoDB;MySQL;Or...,NaN,AWS;DigitalOcean,NaN,Angular;jQuery;Spring,NaN,NaN,NaN,Git;Kubernetes,NaN,Android Studio;IntelliJ;Notepad++;PHPStorm;Vim...,NaN,Windows,Call a coworker or friend;Google it,Stack Overflow,Less than once per month or monthly,No,NaN,Neutral,Yes,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,17500000.0
5306,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United States of America,New Jersey,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,Friend or family member;Books / Physical media,25,5,"Developer, full-stack;DevOps specialist","Just me - I am a freelancer, sole proprietor, ...",USD\tUnited States dollar,3.000000e+05,Weekly,Python,Python;Rust;SQL,NaN,NaN,AWS;Google Cloud Platform,NaN,Flask,Django,NaN,NaN,Ansible;Docker;Git;Terraform,Docker;Git,Vim,Vim,Linux-based,Other (please specify):,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"Yes, somewhat",Yes,35-44 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Too long,Easy,15000000.0
12904,I am a developer by profession,Employed full-time,Serbia,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,1,"Developer, front-end;Developer, full-stack;Dev...",100 to 499 employees,EUR European Euro,1.111000e+06,Monthly,C#;JavaScript;Node.js;Python,C#;Python,MySQL;PostgreSQL,MySQL;PostgreSQL,NaN,NaN,Angular;ASP.NET;ASP.NET Core ;Django;jQuery;Re...,Angular;ASP.NET Core ;Django;React.js,.NET Framework;.NET Core / .NET 5,.NET Core / .NET 5,Docker;Git,Docker;Git,PyCharm;Visual Studio;Visual Studio Code,PyCharm;Visual Studio;Visual Studio Code,Windows,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Daily or almost daily,No,NaN,Neutral,No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Too long,Neither easy nor difficult,14411628.0
66489,I am a developer by profession,Employed full-time,United States of America,Washington,NaN,Some college/university study without earning ...,18 - 24 years,School;Online Courses or Certification;Books /...,5,3,"Developer, desktop or enterprise applications;...",20 to 99 employees,USD\tUnited States dollar,2.550000e+05,Weekly,Bash/Shell;Go;HTML/CSS;Java;JavaScript;Kotlin;...,Node.js;SQL;TypeScript,DynamoDB;Elasticsearch;Firebase;MySQL;PostgreS...,DynamoDB;Redis,AWS;Google Cloud Platform,AWS,Express;React.js;Spring,Express;React.js,NumPy;Pandas,NumPy;Pandas,Docker;Git;Yarn,Git,Atom;IntelliJ;PyCharm;Sublime Text;Visual Stud...,Visual Studio Code,MacOS,Call a coworker or friend;Google it;Meditate,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,Prefer not to say,Prefer not to say,Prefer not to say,Appropriate in length,Easy,12750000.0
47564,I am a developer by profession,Employed full-time,United States of America,Colorado,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Books / Physical media,24,13,"Developer, front-end","10,000 or more employees",USD\tUnited States dollar,2.500000e+05,Weekly,Go;HTML/CSS;JavaScript;Python;TypeScript,HTML/CSS;JavaScript;Python;Rust;TypeScript,PostgreSQL,PostgreSQL,AWS,NaN,React.js;Vue.js,React.js;Vue.js,NaN,NaN,Docker;Git;Kubernetes;Yarn,Git;Yarn,Visual Studio Code,Visual Studio Code,MacOS,Go for a walk or other physical activity;Googl...,Stack Overflow,A few times per month or weekly,Yes,I have never participated in Q&A on Stack Over...,Neutral,No,35-44 years old,Prefer not to say,Prefer not to say,Prefer not to say,Prefer not to say,None of the above,I have an anxiety disorder,Appropriate in length,Neither easy nor difficult,12500000.0